<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Demo Task Title for TestingIni Task _c857b2</name>
   <tag></tag>
   <elementGuidId>1ef42c10-1046-4b56-8117-2809b4cd7602</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='taskval']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#taskval</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-select taskclass valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Choose a Category</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>taskid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>taskval</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Demo Task Title for TestingIni Task Listjjjjjjjjjjjjjjjjmini tiltle taskini tiltle task 2ini tiltle task 3ini tiltle task 4ini tiltle task 5jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjini title taskini taskk  title 7ini taskk  title 7ini taskk  title 7ini title taskiiiiiiiiiiiiiiiiiiiiiiiiiiiiini tiltle task 6titleeeeeeeeeeeeeeeeeeeMembuat Test CaseMembuat Test CaseMembuat Test CaseMembuat Test CaseMembuat Test CaseMembuat Front EndMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan Register!!!!!?????????Desain TopologiMembuat Test CaseTesting Method GETTesting Method POSTMembuat Desain DatabaseMembuat Front EndMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Desain Topologi1111111111111111111111111Testing Method GET1titttleeeeeeeeeeeiniiiiiiiiiiiiiiiiiiiiiiiiiiiiIni title taskTitle Kelender StartTitle Kelender StartTitle Kelender EndMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Title Kelender StartTitle Kelender EndMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Ini title taskIni title taskIni title taskTitle Kelender EndTitle Kelender EndTitle Kelender EndIni title taskTitle Kelender StartTitle Kelender EndMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Mengolah DataIni title taskMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Title Kelender StartTitle Kelender StartTitle Kelender StartIni title taskTitle Kelender StartTitle Kelender EndMembuat Test CaseTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Membuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Ini title taskTitle Kelender StartTitle Kelender EndMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting LoginTesting Halaman Utama !!!!!?????????testing ecommerceMaintenace HardwareBengkel KomputerBengkel Komputer1Bengkel Komputer2jjjjjjjjjjjjjjjjjjjjjjBengkel Komputer3Bengkel Komputer4Bengkel Komputer4asdadasdasdasdaUpdate driverupdate driver1Update Software terbaruUpdate Software terbaruUpdate Software 2022Update Software NewUpdate Hardware Terbaru</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logisticsform&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/select[@id=&quot;taskval&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='taskval']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logisticsform']/div/div/div/div[3]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task List'])[2]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project X23'])[2]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Name'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a Category'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'taskid' and @id = 'taskval' and (text() = '     Demo Task Title for TestingIni Task Listjjjjjjjjjjjjjjjjmini tiltle taskini tiltle task 2ini tiltle task 3ini tiltle task 4ini tiltle task 5jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjini title taskini taskk  title 7ini taskk  title 7ini taskk  title 7ini title taskiiiiiiiiiiiiiiiiiiiiiiiiiiiiini tiltle task 6titleeeeeeeeeeeeeeeeeeeMembuat Test CaseMembuat Test CaseMembuat Test CaseMembuat Test CaseMembuat Test CaseMembuat Front EndMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan Register!!!!!?????????Desain TopologiMembuat Test CaseTesting Method GETTesting Method POSTMembuat Desain DatabaseMembuat Front EndMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Desain Topologi1111111111111111111111111Testing Method GET1titttleeeeeeeeeeeiniiiiiiiiiiiiiiiiiiiiiiiiiiiiIni title taskTitle Kelender StartTitle Kelender StartTitle Kelender EndMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Title Kelender StartTitle Kelender EndMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Ini title taskIni title taskIni title taskTitle Kelender EndTitle Kelender EndTitle Kelender EndIni title taskTitle Kelender StartTitle Kelender EndMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Mengolah DataIni title taskMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Title Kelender StartTitle Kelender StartTitle Kelender StartIni title taskTitle Kelender StartTitle Kelender EndMembuat Test CaseTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Membuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Ini title taskTitle Kelender StartTitle Kelender EndMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting LoginTesting Halaman Utama !!!!!?????????testing ecommerceMaintenace HardwareBengkel KomputerBengkel Komputer1Bengkel Komputer2jjjjjjjjjjjjjjjjjjjjjjBengkel Komputer3Bengkel Komputer4Bengkel Komputer4asdadasdasdasdaUpdate driverupdate driver1Update Software terbaruUpdate Software terbaruUpdate Software 2022Update Software NewUpdate Hardware Terbaru' or . = '     Demo Task Title for TestingIni Task Listjjjjjjjjjjjjjjjjmini tiltle taskini tiltle task 2ini tiltle task 3ini tiltle task 4ini tiltle task 5jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjini title taskini taskk  title 7ini taskk  title 7ini taskk  title 7ini title taskiiiiiiiiiiiiiiiiiiiiiiiiiiiiini tiltle task 6titleeeeeeeeeeeeeeeeeeeMembuat Test CaseMembuat Test CaseMembuat Test CaseMembuat Test CaseMembuat Test CaseMembuat Front EndMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan Register!!!!!?????????Desain TopologiMembuat Test CaseTesting Method GETTesting Method POSTMembuat Desain DatabaseMembuat Front EndMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Desain Topologi1111111111111111111111111Testing Method GET1titttleeeeeeeeeeeiniiiiiiiiiiiiiiiiiiiiiiiiiiiiIni title taskTitle Kelender StartTitle Kelender StartTitle Kelender EndMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Title Kelender StartTitle Kelender EndMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Ini title taskIni title taskIni title taskTitle Kelender EndTitle Kelender EndTitle Kelender EndIni title taskTitle Kelender StartTitle Kelender EndMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Mengolah DataIni title taskMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Title Kelender StartTitle Kelender StartTitle Kelender StartIni title taskTitle Kelender StartTitle Kelender EndMembuat Test CaseTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Membuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseBuat PrediksiMachine Larning ModelBuat DesignTesting Login dan RegisterTesting Halaman Utama !!!!!?????????Ini title taskTitle Kelender StartTitle Kelender EndMembuat Test CaseTesting Method GETTesting Method POSTTesting Method PITCHMembuat Desain DatabaseMembuat Table DatabaseMengolah DataBuat PrediksiMachine Larning ModelBuat DesignTesting LoginTesting Halaman Utama !!!!!?????????testing ecommerceMaintenace HardwareBengkel KomputerBengkel Komputer1Bengkel Komputer2jjjjjjjjjjjjjjjjjjjjjjBengkel Komputer3Bengkel Komputer4Bengkel Komputer4asdadasdasdasdaUpdate driverupdate driver1Update Software terbaruUpdate Software terbaruUpdate Software 2022Update Software NewUpdate Hardware Terbaru')]</value>
   </webElementXpaths>
</WebElementEntity>
